c1_im_path = '../DB/Coin'
c2_im_path = '../DB/Scissors'
min_wdw_sz = [64, 128]
step_size = [10, 10]
orientations = 9
pixels_per_cell = [6, 6]
cells_per_block = [3, 3]
visualize = False
normalize = True
c1_feat_ph = '../DB/dataset1/_features'
c2_feat_ph = '../DB/dataset2/_features'
model_path = '../data/models/'
threshold = .3
